import { Provider } from "react-redux";
import "../styles/globals.scss"
import store from '../app/store';
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Apparel",
  description: "Generated by create next app",
};

function MyApp({ Component, pageProps }) {
  return (
    <Provider store={store}>
      <Component {...pageProps} />
      <Toaster
        toastOptions={{
          position: "top-right",
          style: {
            background: "#283046",
            color: "white",
          },
        }}
      />
      {/* <Toaster
        toastOptions={{
          position: "top-right",
          style: {
            background: "#283046",
            color: "white",
          },
        }}
      /> */}
    </Provider>
  );}

export default MyApp;

